config/routes.rb
Rails.application.routes.draw do
  get 'games/home'

  get 'games/new_match'

  get 'games/show_ranking'

  get 'games/edit'

  get 'games/destroy'

  post 'games/new_multiple_match'

  get 'games/new_challenge'

  post 'games/create_match'

  get 'games/:id/show_match_game', to: 'games#show_match_game', as: "show_match_game"

  post 'games/:id/save_results', to: 'games#save_results', as: "save_results"

  get 'games/show_winner/:id', to: 'games#show_winner', as: "show_winner"

  get 'games/:id/show_multiple_match_game', to: 'games#show_multiple_match_game', as: "show_multiple_match_game" 

  get 'games/see_my_games'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root to:"games#home"
devise_for :users, controllers: {
        sessions: 'users/sessions'
      }

end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :opponent, class_name: 'User', optional: true, foreign_key: "opponent_id"
  belongs_to :player, class_name: 'User', optional: true, foreign_key: "player_id"
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
    before_action :authenticate_user!, :except => :home


  def home
  end

  def new_match
    call_players
  end

  def create_match
    @match=Game.new
    @match.player = current_user
    @match.opponent = User.find(params[:opponent])
    @match.game_type = params[:type]
    @match.save
    if @match.game_type === "single_match"
      redirect_to show_match_game_path(@match.id)
    elsif @match.game_type === "multiple_match"
      redirect_to show_multiple_match_game_path(@match.id)
    end
  end

  def show_match_game
    access_players
  end

  def show_multiple_match_game
    access_players
  end

  def save_results
    @winner
    access_players
    if @game.game_type == "single_match"
      @game.score_player=params[:results_player].to_i
      @game.score_opponent=params[:results_opponent].to_i
      @game.save
      @winner = params[:winner]
      if @winner === "player"
        @player.score = @player.score + 1
        @player.save
      elsif @winner === "opponent"
        @opponent.score = @opponent.score + 1
        @opponent.save
      else
        redirect_to new_match_path
      end
    elsif @game.game_type == "multiple_match"
      @winner = [params[:winner1], params[:winner2], params[:winner3]]
      counter = 0
      @winner.each do |w|
        if w === "player"
          counter += 1
        elsif w === "opponent"
          counter = counter - 1
        end
      end
      if counter > 0
        @player.score += 3
        @player.save
      else
        @opponent.score += 3
        @opponent.save
      end
    end
    redirect_to games_show_ranking_path
  end

  def show_ranking
    @players=User.all
    @players=@players.where.not(:score => nil).sort_by(&:score).reverse
  end

  def new_challenge
    call_players
  end

  def edit
  end

  def destroy
  end

  def see_my_games
    @games=Game.where("player_id = #{current_user.id} OR opponent_id = #{current_user.id}")
    @games=@games.sort_by(&:created_at).reverse
  end

private

  def call_players
    @player= current_user
    if @player.score == nil
      @player.score = 0
      @player.save
    end
    @opponents= User.where.not(:id => current_user.id)
    @opponents.each do |o|
      if o.score == nil
        o.score = 0
        o.save
      end
    end
  end

  def access_players
    @game=Game.find(params[:id])
    @player=User.find(@game.player_id)
    @opponent=User.find(@game.opponent_id)
  end

end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/destroy,.html.erb
<h1>Games#destroy,</h1>
<p>Find me in app/views/games/destroy,.html.erb</p>

app/views/games/destroy.html.erb
<h1>Games#destroy,</h1>
<p>Find me in app/views/games/destroy,.html.erb</p>

app/views/games/edit,.html.erb
<h1>Games#edit,</h1>
<p>Find me in app/views/games/edit,.html.erb</p>

app/views/games/edit.html.erb
<h1>Games#edit,</h1>
<p>Find me in app/views/games/edit,.html.erb</p>

app/views/games/home.html.erb
<div class="container-fluid img-responsive">
  <div class="col-sm-8 col-sm-offset-2 text-center">
    <h1>Ping Pong Match</h1>
    <br>
    <br>
    <p>
      Una aplicacion desarrollada para los aficionados la Ping Pong, en ella podras llevar el registro de tus juegos con otros usuarios; ademas podras retar a aquellos con los que aun no has jugado y lograr ser el REY DE LA CANCHA
    </p>
    <br>
    <br>
    <div class="row">
      <div class="btn btn-success col-xs-4 col-xs-offset-4">
        <%=link_to "Nueva Partida", games_new_match_path, method: "get"%>
      </div>
    </div>
    <br>
    <div class="row">
      <div class="btn btn-success col-xs-4 col-xs-offset-4">
        <%=link_to "Ranking", games_show_ranking_path, method: "get"%>
      </div>
    </div>
    <br>
    <div class="row">
      <div class="btn btn-success col-xs-4 col-xs-offset-4">
        <%=link_to "Retar", games_new_challenge_path, method: "get"%>
      </div>
    </div>
  </div>
  <br>
  <br>
</div>

app/views/games/new_challenge.html.erb
<h1>Nuevo reto</h1>


	<%= form_tag games_create_match_path, method: :post, class: "col-xs-12" do %>
			<%= select_tag :opponent , options_from_collection_for_select(@opponents, "id", "nick_name"), {:multiple => false, :required => true, :size => 10, :class => "form-control"}%>
	<%end%>

app/views/games/new_match.html.erb
<div class="col-md-8 col-xs-12 col-md-offset-2 text-center">
	<h1>Nueva Partida</h1>
	<br>
	<br>
	<div class="col-md-5 text-center">
		<h4>Jugador</h4>
		<p>
		<%= @player.nick_name %>
		</p>
	</div>
	<div class="col-md-2">
		<h3>VS</h3>
	</div>
	<div class="col-md-5 text-center">
		<h4>Oponentes</h4>
		<%= form_tag games_create_match_path, method: :post, class: "col-xs-12" do %>
			<%= select_tag :opponent , options_from_collection_for_select(@opponents, "id", "nick_name"), {:multiple => false, :required => true, :size => 10, :class => "form-control"}%>
			<br>
			<%= radio_button_tag(:type, "single_match") %>
			<%= label_tag(:match, "Partida simple") %>
			<br>
			<%= radio_button_tag(:type, "multiple_match") %>
			<%= label_tag(:multiple_match, "Partida Multiple") %>
			<br>
			<%= submit_tag "Retar", class: "btn btn-success" %>
		<%end%>
	</div>
</div>

app/views/games/see_my_games.html.erb
<h1>Lista de juegos</h1>

<div>
	<table class="table table-bordered">
		<thead>
			<tr>
				<th>Jugador</th>
				<th>Oponente</th>
				<th>Fecha</th>
			</tr>
		</thead>
		<tbody>
			<%@games.each do |g|%>
				<%player=User.find(g.player_id)%>
				<%opponent=User.find(g.opponent_id)%>
				<tr>
					<td><%=player.nick_name%></td>
					<td><%=opponent.nick_name%></td>
					<td><%=g.created_at%></td>
				</tr>
			<%end%>
		</tbody>
	</table>
</div>

app/views/games/show_match_game.html.erb
<%= form_tag save_results_path , method: 'post' do %>
  <div class="row">
    <div class="col-sm-5 text-center">
      <h3>Jugador</h3>
      <p>
        <%=@player.nick_name%>
      </p>
      <br>
      <%= radio_button_tag(:winner, "player") %>
      <br>
      <%= number_field_tag :results_player, 0, :min => 0%>
    </div>
    <div class="col-sm-2 text-center">
      <h3>VS</h3>
    </div>
    <div class="col-sm-5 text-center">
      <h3>Oponente</h3>
      <p>
        <%=@opponent.nick_name%>
      </p>
      <br>
      <%= radio_button_tag(:winner, "opponent") %>
      <br>
      <%= number_field_tag :results_opponent, 0, :min => 0%>
    </div>
  <br>
  <br>
  <div class="col-sm-12 text-center">
    <%= submit_tag "Guardar", class: "btn btn-success" %>
  </div>
<%end%>

app/views/games/show_multiple_match_game.html.erb
  <%= form_tag save_results_path , method: 'post' do %>
  <div class="col-sm-5 text-center">
    <h3>Jugador</h3>
    <p>
      <%=@player.nick_name%>
    </p>
    <%= radio_button_tag(:winner1, "player") %>
    <%= label_tag(:winner1, "Primer Partido") %>
    <br>
    <%= radio_button_tag(:winner2, "player") %>
    <%= label_tag(:winner2, "Segundo Partido") %>
    <br>
    <%= radio_button_tag(:winner3, "player") %>
    <%= label_tag(:winner3, "Tercer Partido") %>
    <br>
  </div>
  <div class="col-sm-2 text-center">
    <h3>VS</h3>
  </div>
  <div class="col-sm-5 text-center">
    <h3>Oponente</h3>
    <p>
      <%=@opponent.nick_name%>
    </p>
    <%= radio_button_tag(:winner1, "opponent") %>
    <%= label_tag(:winner1, "Primer Partido") %>
    <br>
    <%= radio_button_tag(:winner2, "opponent") %>
    <%= label_tag(:winner2, "Segundo Partido") %>
    <br>
    <%= radio_button_tag(:winner3, "opponent") %>
    <%= label_tag(:winner3, "Tercer Partido") %>
    <br>
  </div>
  <div class="col-sm-12 text-center">
    <%= submit_tag "Guardar", class: "btn btn-success" %>
  </div>
  <%end%>

app/views/games/show_ranking.html.erb
<div class="text-center">

<h1>Ranking</h1>

<h2>El rey de la cancha es!!!!</h2>
<h3><%=@players[0].nick_name%></h3>
<p>con <%=@players[0].score%> puntos</p>
  <div class="col-sm-6 col-sm-offset-3">
    <table class="table table-bordered text-center">
      <thead>
        <tr>
          <th>
            Jugador
          </th>
          <th>
            Puntaje
          </th>
        </tr>
      </thead>
      <tbody>
      <%@players.each do |p|%>
        <%if p != @players[0]%>
          <tr>
            <td>
              <%=p.nick_name%>
            </td>
            <td>
              <%=p.score%>
            </td>
          </tr>
        <%end%>
      <%end%>
      </tbody>
    </table>
  </div>
</div>
<br>
<br>
  <div class="col-xs-12 text-center">
    <button type="button" name="button" class="btn btn-success">
      <a href="/games/new_match">Nueva Partida</a>
    </button>
  </div>