config/routes.rb
Rails.application.routes.draw do
  get 'games/home'

  get 'games/new_match'

  get 'games/show_ranking'

  get 'games/edit'

  get 'games/destroy'

  post 'games/new_multiple_match'

  get 'games/new_challenge'

  post 'games/create_match'

  get 'games/:id/show_match_game', to: 'games#show_match_game', as: "show_match_game"

  post 'games/:id/save_results', to: 'games#save_results', as: "save_results"

  get 'games/show_winner/:id', to: 'games#show_winner', as: "show_winner"

  get 'games/:id/show_multiple_match_game', to: 'games#show_multiple_match_game', as: "show_multiple_match_game" 

  get 'games/see_my_games'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root to:"games#home"
devise_for :users, controllers: {
        sessions: 'users/sessions'
      }

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PingPong</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="navbar-text pull-right">
      <% if user_signed_in? %>
        Bienvenido <strong><%= current_user.nick_name %></strong>
        <div class="btn btn-primary">
          <%= link_to 'Inicio', root_path, :class => 'navbar-link' %>
        </div>
        <div class="btn btn-success">
        <%= link_to 'Mi Perfil', edit_user_registration_path, :class => 'navbar-link' %>
        </div>
        <div class="btn btn-warning">
        <%= link_to 'Mis Juegos', games_see_my_games_path, :class => 'navbar-link' %> 
        </div>
        <div class="btn btn-danger">
        <%= link_to "Cerrar Sesión", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
        </div>
      <% else %>
        <%= link_to "Registrarse", new_user_registration_path, :class => 'navbar-link'  %> |
        <%= link_to "Iniciar Sesión", new_user_session_path, :class => 'navbar-link'  %>
      <% end %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

      <div class="field col-sm-8 col-sm-offset-2">
        <div>
          <%= yield %>
        </div>
      </div>
  </body>
</html>